### ISSUE TITLE
Corrección de errores

### ISSUE THREAD

**Issue by NicoMM8** [NicoMM8/2022PCTR_2CMunoz_Nicolas#10]
**Una vez(completado) el código implementando teóricamente las reglas avanzadas, necesito corregir el código ya que da varios errores.**
Exception in thread "Thread-1" java.lang.IllegalStateException: El invariante de los contadores de enemigos vivos no se cumple
	at Juego.generarEnemigo(Juego.java:34)
	at ActividadEnemiga.run(ActividadEnemiga.java:34)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Thread-5" java.lang.IllegalStateException: El invariante de los contadores de enemigos vivos no se cumple
	at Juego.generarEnemigo(Juego.java:34)

**Comment by NicoMM8** [comment]
Era un error de donde ejecución, ya que aparecía que el programa ejecutase el proyecto desde 2022PCTR_2CMunoz_Nicolas/src, y los archivos se encontraban en la raíz de la carpeta, por lo que simplemente era modificar eso.
También tuve errores de escritura y en relación a alguna variable que no estaba donde debía estar. Pero ya está todo solucionado.
